---
antora:
  name: modules
  dir: www
  modules:
    # Section 1: Command-line Ansible Exercises
    - name: module-01
      label: "1. Writing Your First Playbook"
      solveButton: false
    - name: module-02
      label: "2. Using Variables"
      solveButton: false

    # Section 2: Ansible Automation Platform Exercises
    - name: module-10
      label: "3. Projects & Job Templates"
      solveButton: false
    - name: module-11
      label: "4. Surveys"
      solveButton: false
    - name: module-12
      label: "5. Role-based Access Control"
      solveButton: false
    - name: module-14
      label: "6. System Roles"
      solveButton: false
    - name: module-15
      label: "7. Wrap Up"
      solveButton: false

tabs:
  - name: AAP
    url: https://control-${guid}.${domain}/
    external: false
    modules:
      - module-01
      - module-02
      - module-10
      - module-11
      - module-12
      - module-14
      - module-15
  - name: VS Code
    url: https://vscode-${guid}.${domain}/
    external: false
    modules:
      - module-01
      - module-02
      - module-10
      - module-11
      - module-12
      - module-14
      - module-15
