---
virtualmachines:
  # Ansible Automation Platform Control Node
  - name: "control"
    image: "aap-2.6-6-ceh-20260325"
    memory: "32G"
    cores: 4
    image_size: "50Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
    services:
      - name: control
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: control-https
          - port: 22
            protocol: TCP
            targetPort: 22
            name: control-ssh
    routes:
      - name: control-https
        host: control
        service: control
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIF1jCCA76gAwIBAgIUDDMiIDzSJRTuX95rAge4OUEro48wDQYJKoZIhvcNAQEL
          BQAwgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
          A1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEQMA4GA1UECwwHQW5zaWJs
          ZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0aW9uIFBsYXRmb3JtMB4XDTI2MDMy
          NTIxNDIxMFoXDTM2MDMyMjIxNDIxMFowgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQI
          DA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVk
          IEhhdDEQMA4GA1UECwwHQW5zaWJsZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0
          aW9uIFBsYXRmb3JtMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEApeIb
          6Chw4kCGby02krwND3s5FyX5alaaoQ0UyrKqg7XCkUNfSxW+Q/2HKkt4GoswBSpc
          eCCIzXZdHfcuIpAMgZqOTjPDBszOGznhji4KsN2uv/8ACV7ddCD012PgGhimiT7A
          hznrUP977LV/4CwOc+NKes8uf2WrFSq11PI5upmsQQ3lFfAhK4ZWT4OMLTY0Kwg1
          YgwquLaXg+60gcdAAiGRJcrc4stkYFn6mtSur5LF6Ni/6PAjCpRzkzzIL2LIR2Ha
          4W1lMkHryzqswTQfMkPy24OtA23jBG+bT0s9cyyLQUGGqAL4XWCUikFHw70QUGOl
          ans28lUS7ptTOiENTcaVEUYcnnAKjMadHsCIs1q9DQ3cGMhyZvf/SQhSYMUGxgM1
          fRfNQ4YXchun681V3eJ4OkZwOedPAR/gFpmo80d+zG/SSa4PKhfwr7ZcSN8cT097
          IIY6E4FOOiQrqM2MUxmZvQhVdkDBkcKNDE6Se/qZnN6TtQ+vpFjZEz41jmZ84Ntg
          z86W3sTUczph1z9FyrweMNgiNOseJUQIHxxd3Vs7Or3BmIlmwiaHz781pabyv3Xo
          yfBAHYllnmXXOWfC9HOC7tTL37FzzLx5xOElEZvMMuKa1AYSHMn8zfHeg9SSzX5R
          eEsHw9ez2VLb8FeR0a7SAwZi8MAxG1M2hEAD8b8CAwEAAaNCMEAwDgYDVR0PAQH/
          BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFPI7IBYU6oA9yPLyQ2/s
          LUHsxbgjMA0GCSqGSIb3DQEBCwUAA4ICAQBkWvWQouV3dcBULh2EP/ZEJ6GvB5l8
          ByeyYgPVy2OpFyV/MDKkk60lMxnBASNRwOk0wY1ABRKItnOjIHT6B9Og4Vr6vdRG
          r9vOiayMiiGhWty8mM+XZ7ATznncjqqtpPlI7k6QGXAjmSlTfkZe3VyFwj38p4RY
          HgCGne+mld3wcJ5uBV1QGS7VnqIe4dbN9M5KOloJGVfUeAn1oVq7TTQ49s4w8X1n
          gtA/wZYmrQXt63/AvbkzXPqTwLhUPKH95tXo6SvqJ1coqjPI7bYN/aWnAnGbgy9j
          TKxNYKHlCpmLlog3ucgKEgDoQpgl2NmGU5EFvs4R7mVKrAtQmBwihSYg6xlLDtiC
          nGnuY1ZXCejKIZjDGmS1RySQOB81bDcI3weY0FoLQOU6Y+Tp/uR16MrE1JL75zaS
          dzSAvNgZ8EJU08xtF9Pym91pOOHkVlXFkNnogUlBU3Lp4QWGPaqP+ubWnQmwr9O2
          6au2oZWhBUmDwO5o2VhqlbPXsdL9mA/sXY4EvGuFynO30XDGqilSvjgzFcwaxJDx
          84qKac3RhIWrQw1t4CD557ngPJpJAoH+T+UCADG3hw6ufV/MmingXXT2D+nh1U3S
          zx74taEi67dEv3p+uBY13JIK0SI6iEQKcVjhWYwv1j/wgTibd9lJZYhfF6iqe8gs
          UBMDh252dR3Mqg==
          -----END CERTIFICATE-----

  - name: "node01"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

  - name: "node02"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node02-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node02
    routes:
      - name: node02-web
        host: node02
        service: node02-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
        
  - name: "node03"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node03-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node03
    routes:
      - name: node03-web
        host: node03
        service: node03-http
        targetPort: 80
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd


  - name: "vscode"
    image: "devtools-ansible"
    memory: "8G"
    cores: 2
    image_size: "20Gi"
    disk_type: "scsi"
    bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: vscode-8080
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: vscode
    routes:
      - name: vscode-8080
        host: vscode
        service: vscode-8080
        targetPort: 8080
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
